// Code generated by entimport, DO NO2T EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type Product struct {
	ent.Schema
}

func (Product) Fields() []ent.Field {
	return []ent.Field{field.Uint64("id"),
		field.Time("created_at").Optional(),
		field.Time("updated_at").Optional(),
		field.Time("deleted_at").Optional(),
		field.String("app_id").Unique(),
		field.Int64("app_type").Default(0), // 0-个人 1-收款
		field.String("app_name"),
		field.String("app_secret"),
		field.Int64("app_status"),
		field.Int64("withdraw_status"),
		field.String("web_hook")}
}
func (Product) Edges() []ent.Edge {
	return nil
}
func (Product) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "product"}}
}
