// Code generated by ent, DO NOT EDIT.

package txn

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the txn type in the database.
	Label = "txn"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldTxID holds the string denoting the tx_id field in the database.
	FieldTxID = "tx_id"
	// FieldChainID holds the string denoting the chain_id field in the database.
	FieldChainID = "chain_id"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldFromAddress holds the string denoting the from_address field in the database.
	FieldFromAddress = "from_address"
	// FieldToAddress holds the string denoting the to_address field in the database.
	FieldToAddress = "to_address"
	// FieldAmountStr holds the string denoting the amount_str field in the database.
	FieldAmountStr = "amount_str"
	// FieldAmountRaw holds the string denoting the amount_raw field in the database.
	FieldAmountRaw = "amount_raw"
	// FieldHandleStatus holds the string denoting the handle_status field in the database.
	FieldHandleStatus = "handle_status"
	// FieldHandleMsg holds the string denoting the handle_msg field in the database.
	FieldHandleMsg = "handle_msg"
	// FieldHandleTime holds the string denoting the handle_time field in the database.
	FieldHandleTime = "handle_time"
	// FieldCollectStatus holds the string denoting the collect_status field in the database.
	FieldCollectStatus = "collect_status"
	// FieldCollectMsg holds the string denoting the collect_msg field in the database.
	FieldCollectMsg = "collect_msg"
	// FieldCollectTime holds the string denoting the collect_time field in the database.
	FieldCollectTime = "collect_time"
	// Table holds the table name of the txn in the database.
	Table = "txn"
)

// Columns holds all SQL columns for txn fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldTxID,
	FieldChainID,
	FieldProductID,
	FieldFromAddress,
	FieldToAddress,
	FieldAmountStr,
	FieldAmountRaw,
	FieldHandleStatus,
	FieldHandleMsg,
	FieldHandleTime,
	FieldCollectStatus,
	FieldCollectMsg,
	FieldCollectTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt time.Time
	// DefaultHandleStatus holds the default value on creation for the "handle_status" field.
	DefaultHandleStatus int64
	// DefaultCollectStatus holds the default value on creation for the "collect_status" field.
	DefaultCollectStatus int64
)

// OrderOption defines the ordering options for the Txn queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByTxID orders the results by the tx_id field.
func ByTxID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTxID, opts...).ToFunc()
}

// ByChainID orders the results by the chain_id field.
func ByChainID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChainID, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByFromAddress orders the results by the from_address field.
func ByFromAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromAddress, opts...).ToFunc()
}

// ByToAddress orders the results by the to_address field.
func ByToAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToAddress, opts...).ToFunc()
}

// ByAmountStr orders the results by the amount_str field.
func ByAmountStr(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountStr, opts...).ToFunc()
}

// ByAmountRaw orders the results by the amount_raw field.
func ByAmountRaw(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountRaw, opts...).ToFunc()
}

// ByHandleStatus orders the results by the handle_status field.
func ByHandleStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHandleStatus, opts...).ToFunc()
}

// ByHandleMsg orders the results by the handle_msg field.
func ByHandleMsg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHandleMsg, opts...).ToFunc()
}

// ByHandleTime orders the results by the handle_time field.
func ByHandleTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHandleTime, opts...).ToFunc()
}

// ByCollectStatus orders the results by the collect_status field.
func ByCollectStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectStatus, opts...).ToFunc()
}

// ByCollectMsg orders the results by the collect_msg field.
func ByCollectMsg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectMsg, opts...).ToFunc()
}

// ByCollectTime orders the results by the collect_time field.
func ByCollectTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectTime, opts...).ToFunc()
}
