// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skyisboss/pay-system/ent/predicate"
	"github.com/skyisboss/pay-system/ent/product"
)

// ProductUpdate is the builder for updating Product entities.
type ProductUpdate struct {
	config
	hooks    []Hook
	mutation *ProductMutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (pu *ProductUpdate) Where(ps ...predicate.Product) *ProductUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetCreatedAt sets the "created_at" field.
func (pu *ProductUpdate) SetCreatedAt(t time.Time) *ProductUpdate {
	pu.mutation.SetCreatedAt(t)
	return pu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableCreatedAt(t *time.Time) *ProductUpdate {
	if t != nil {
		pu.SetCreatedAt(*t)
	}
	return pu
}

// ClearCreatedAt clears the value of the "created_at" field.
func (pu *ProductUpdate) ClearCreatedAt() *ProductUpdate {
	pu.mutation.ClearCreatedAt()
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *ProductUpdate) SetUpdatedAt(t time.Time) *ProductUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableUpdatedAt(t *time.Time) *ProductUpdate {
	if t != nil {
		pu.SetUpdatedAt(*t)
	}
	return pu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (pu *ProductUpdate) ClearUpdatedAt() *ProductUpdate {
	pu.mutation.ClearUpdatedAt()
	return pu
}

// SetDeletedAt sets the "deleted_at" field.
func (pu *ProductUpdate) SetDeletedAt(t time.Time) *ProductUpdate {
	pu.mutation.SetDeletedAt(t)
	return pu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableDeletedAt(t *time.Time) *ProductUpdate {
	if t != nil {
		pu.SetDeletedAt(*t)
	}
	return pu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (pu *ProductUpdate) ClearDeletedAt() *ProductUpdate {
	pu.mutation.ClearDeletedAt()
	return pu
}

// SetAppID sets the "app_id" field.
func (pu *ProductUpdate) SetAppID(s string) *ProductUpdate {
	pu.mutation.SetAppID(s)
	return pu
}

// SetAppName sets the "app_name" field.
func (pu *ProductUpdate) SetAppName(s string) *ProductUpdate {
	pu.mutation.SetAppName(s)
	return pu
}

// SetAppSecret sets the "app_secret" field.
func (pu *ProductUpdate) SetAppSecret(s string) *ProductUpdate {
	pu.mutation.SetAppSecret(s)
	return pu
}

// SetAppStatus sets the "app_status" field.
func (pu *ProductUpdate) SetAppStatus(i int64) *ProductUpdate {
	pu.mutation.ResetAppStatus()
	pu.mutation.SetAppStatus(i)
	return pu
}

// AddAppStatus adds i to the "app_status" field.
func (pu *ProductUpdate) AddAppStatus(i int64) *ProductUpdate {
	pu.mutation.AddAppStatus(i)
	return pu
}

// SetWithdrawStatus sets the "withdraw_status" field.
func (pu *ProductUpdate) SetWithdrawStatus(i int64) *ProductUpdate {
	pu.mutation.ResetWithdrawStatus()
	pu.mutation.SetWithdrawStatus(i)
	return pu
}

// AddWithdrawStatus adds i to the "withdraw_status" field.
func (pu *ProductUpdate) AddWithdrawStatus(i int64) *ProductUpdate {
	pu.mutation.AddWithdrawStatus(i)
	return pu
}

// SetWebHook sets the "web_hook" field.
func (pu *ProductUpdate) SetWebHook(s string) *ProductUpdate {
	pu.mutation.SetWebHook(s)
	return pu
}

// Mutation returns the ProductMutation object of the builder.
func (pu *ProductUpdate) Mutation() *ProductMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProductUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProductUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProductUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProductUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *ProductUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeUint64))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.CreatedAt(); ok {
		_spec.SetField(product.FieldCreatedAt, field.TypeTime, value)
	}
	if pu.mutation.CreatedAtCleared() {
		_spec.ClearField(product.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(product.FieldUpdatedAt, field.TypeTime, value)
	}
	if pu.mutation.UpdatedAtCleared() {
		_spec.ClearField(product.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := pu.mutation.DeletedAt(); ok {
		_spec.SetField(product.FieldDeletedAt, field.TypeTime, value)
	}
	if pu.mutation.DeletedAtCleared() {
		_spec.ClearField(product.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := pu.mutation.AppID(); ok {
		_spec.SetField(product.FieldAppID, field.TypeString, value)
	}
	if value, ok := pu.mutation.AppName(); ok {
		_spec.SetField(product.FieldAppName, field.TypeString, value)
	}
	if value, ok := pu.mutation.AppSecret(); ok {
		_spec.SetField(product.FieldAppSecret, field.TypeString, value)
	}
	if value, ok := pu.mutation.AppStatus(); ok {
		_spec.SetField(product.FieldAppStatus, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.AddedAppStatus(); ok {
		_spec.AddField(product.FieldAppStatus, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.WithdrawStatus(); ok {
		_spec.SetField(product.FieldWithdrawStatus, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.AddedWithdrawStatus(); ok {
		_spec.AddField(product.FieldWithdrawStatus, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.WebHook(); ok {
		_spec.SetField(product.FieldWebHook, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProductUpdateOne is the builder for updating a single Product entity.
type ProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductMutation
}

// SetCreatedAt sets the "created_at" field.
func (puo *ProductUpdateOne) SetCreatedAt(t time.Time) *ProductUpdateOne {
	puo.mutation.SetCreatedAt(t)
	return puo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableCreatedAt(t *time.Time) *ProductUpdateOne {
	if t != nil {
		puo.SetCreatedAt(*t)
	}
	return puo
}

// ClearCreatedAt clears the value of the "created_at" field.
func (puo *ProductUpdateOne) ClearCreatedAt() *ProductUpdateOne {
	puo.mutation.ClearCreatedAt()
	return puo
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *ProductUpdateOne) SetUpdatedAt(t time.Time) *ProductUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableUpdatedAt(t *time.Time) *ProductUpdateOne {
	if t != nil {
		puo.SetUpdatedAt(*t)
	}
	return puo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (puo *ProductUpdateOne) ClearUpdatedAt() *ProductUpdateOne {
	puo.mutation.ClearUpdatedAt()
	return puo
}

// SetDeletedAt sets the "deleted_at" field.
func (puo *ProductUpdateOne) SetDeletedAt(t time.Time) *ProductUpdateOne {
	puo.mutation.SetDeletedAt(t)
	return puo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableDeletedAt(t *time.Time) *ProductUpdateOne {
	if t != nil {
		puo.SetDeletedAt(*t)
	}
	return puo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (puo *ProductUpdateOne) ClearDeletedAt() *ProductUpdateOne {
	puo.mutation.ClearDeletedAt()
	return puo
}

// SetAppID sets the "app_id" field.
func (puo *ProductUpdateOne) SetAppID(s string) *ProductUpdateOne {
	puo.mutation.SetAppID(s)
	return puo
}

// SetAppName sets the "app_name" field.
func (puo *ProductUpdateOne) SetAppName(s string) *ProductUpdateOne {
	puo.mutation.SetAppName(s)
	return puo
}

// SetAppSecret sets the "app_secret" field.
func (puo *ProductUpdateOne) SetAppSecret(s string) *ProductUpdateOne {
	puo.mutation.SetAppSecret(s)
	return puo
}

// SetAppStatus sets the "app_status" field.
func (puo *ProductUpdateOne) SetAppStatus(i int64) *ProductUpdateOne {
	puo.mutation.ResetAppStatus()
	puo.mutation.SetAppStatus(i)
	return puo
}

// AddAppStatus adds i to the "app_status" field.
func (puo *ProductUpdateOne) AddAppStatus(i int64) *ProductUpdateOne {
	puo.mutation.AddAppStatus(i)
	return puo
}

// SetWithdrawStatus sets the "withdraw_status" field.
func (puo *ProductUpdateOne) SetWithdrawStatus(i int64) *ProductUpdateOne {
	puo.mutation.ResetWithdrawStatus()
	puo.mutation.SetWithdrawStatus(i)
	return puo
}

// AddWithdrawStatus adds i to the "withdraw_status" field.
func (puo *ProductUpdateOne) AddWithdrawStatus(i int64) *ProductUpdateOne {
	puo.mutation.AddWithdrawStatus(i)
	return puo
}

// SetWebHook sets the "web_hook" field.
func (puo *ProductUpdateOne) SetWebHook(s string) *ProductUpdateOne {
	puo.mutation.SetWebHook(s)
	return puo
}

// Mutation returns the ProductMutation object of the builder.
func (puo *ProductUpdateOne) Mutation() *ProductMutation {
	return puo.mutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (puo *ProductUpdateOne) Where(ps ...predicate.Product) *ProductUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProductUpdateOne) Select(field string, fields ...string) *ProductUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Product entity.
func (puo *ProductUpdateOne) Save(ctx context.Context) (*Product, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProductUpdateOne) SaveX(ctx context.Context) *Product {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProductUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProductUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *ProductUpdateOne) sqlSave(ctx context.Context) (_node *Product, err error) {
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeUint64))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Product.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, product.FieldID)
		for _, f := range fields {
			if !product.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != product.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.CreatedAt(); ok {
		_spec.SetField(product.FieldCreatedAt, field.TypeTime, value)
	}
	if puo.mutation.CreatedAtCleared() {
		_spec.ClearField(product.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(product.FieldUpdatedAt, field.TypeTime, value)
	}
	if puo.mutation.UpdatedAtCleared() {
		_spec.ClearField(product.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := puo.mutation.DeletedAt(); ok {
		_spec.SetField(product.FieldDeletedAt, field.TypeTime, value)
	}
	if puo.mutation.DeletedAtCleared() {
		_spec.ClearField(product.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := puo.mutation.AppID(); ok {
		_spec.SetField(product.FieldAppID, field.TypeString, value)
	}
	if value, ok := puo.mutation.AppName(); ok {
		_spec.SetField(product.FieldAppName, field.TypeString, value)
	}
	if value, ok := puo.mutation.AppSecret(); ok {
		_spec.SetField(product.FieldAppSecret, field.TypeString, value)
	}
	if value, ok := puo.mutation.AppStatus(); ok {
		_spec.SetField(product.FieldAppStatus, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.AddedAppStatus(); ok {
		_spec.AddField(product.FieldAppStatus, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.WithdrawStatus(); ok {
		_spec.SetField(product.FieldWithdrawStatus, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.AddedWithdrawStatus(); ok {
		_spec.AddField(product.FieldWithdrawStatus, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.WebHook(); ok {
		_spec.SetField(product.FieldWebHook, field.TypeString, value)
	}
	_node = &Product{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
