// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Addres is the predicate function for addres builders.
type Addres func(*sql.Selector)

// Apprun is the predicate function for apprun builders.
type Apprun func(*sql.Selector)

// Balance is the predicate function for balance builders.
type Balance func(*sql.Selector)

// Blockchain is the predicate function for blockchain builders.
type Blockchain func(*sql.Selector)

// Notify is the predicate function for notify builders.
type Notify func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Transfer is the predicate function for transfer builders.
type Transfer func(*sql.Selector)

// Txn is the predicate function for txn builders.
type Txn func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Withdraw is the predicate function for withdraw builders.
type Withdraw func(*sql.Selector)
